select
	smn_base.smn_item.itm_nombre as catalogo,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_descripcion_ingrediente as descripcion,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_cantidad as cantidad,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_requirimientos as requerimientos,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_precio_ml,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_cantidad*smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_precio_ml as sed_monto_moneda_local,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_solicitud_servicio_entregas_detalle_id,
	smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_descripcion as smn_solicitud_servicio_entregas_cabecera_id,
	smn_base.smn_unidad_medida.unm_descripcion as smn_unidad_medida_rf,
	case
	when smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_estatus_proceso='SO' then '${lbl:b_solicitada}'
	when smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_estatus_proceso='AC' then '${lbl:b_aprobada_comercio}'
	when smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_estatus_proceso='AS' then '${lbl:b_aprobada_solicitante}'
	when smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_estatus_proceso='EP' then '${lbl:b_en_proceso}'
	when smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_estatus_proceso='DE' then '${lbl:b_despachado}'
	when smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_estatus_proceso='EN' then '${lbl:b_entregado}'
	when smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_estatus_proceso='RE' then '${lbl:b_rechazado}'
	when smn_comercial.smn_solicitud_servicio_entregas_cabecera.sec_estatus_proceso='ER' then 'En Despacho'
	end as sec_estatus_proceso,
	smn_base.smn_unidad_medida.smn_unidad_medida_id as smn_unidad_medida_rf1,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_fecha_registro
from
	smn_comercial.smn_solicitud_servicio_entregas_detalle	
	left outer join smn_comercial.smn_solicitud_servicio_entregas_cabecera on smn_comercial.smn_solicitud_servicio_entregas_cabecera.smn_solicitud_servicio_entregas_cabecera_id = smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_solicitud_servicio_entregas_cabecera_id
	left outer join smn_base.smn_unidad_medida on smn_base.smn_unidad_medida.smn_unidad_medida_id = smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_unidad_medida_rf
	left outer join smn_base.smn_monedas on smn_base.smn_monedas.smn_monedas_id = smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_moneda_rf
	inner join smn_comercial.smn_catalogo_item_comercio on smn_comercial.smn_catalogo_item_comercio.smn_catalogo_item_comercio_id = smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_catalogo_item_comercio_id
	inner join smn_base.smn_item on smn_base.smn_item.smn_item_id = smn_comercial.smn_catalogo_item_comercio.smn_item_rf
where
	smn_comercial.smn_solicitud_servicio_entregas_cabecera.smn_solicitud_servicio_entregas_cabecera_id=${fld:id2}