select smn_base.smn_servicios.smn_servicios_id as id, smn_base.smn_servicios.svc_descripcion as item from smn_base.smn_servicios
inner join smn_comercial.smn_rel_linea_comercial_servicio on smn_comercial.smn_rel_linea_comercial_servicio.smn_servicio_rf = smn_base.smn_servicios.smn_servicios_id
inner join smn_comercial.smn_rel_centro_fac_linea on smn_comercial.smn_rel_centro_fac_linea.smn_linea_comercial_id = smn_comercial.smn_rel_linea_comercial_servicio.smn_linea_comercial_id
inner join smn_comercial.smn_centro_facturacion on smn_comercial.smn_centro_facturacion.smn_centro_facturacion_id = smn_comercial.smn_rel_centro_fac_linea.smn_centro_facturacion_id
WHERE
smn_comercial.smn_rel_linea_comercial_servicio.smn_linea_comercial_id=${fld:id} and smn_comercial.smn_centro_facturacion.smn_entidades_rf=${fld:entidad}  and smn_comercial.smn_centro_facturacion.smn_baremos_rf=${fld:baremos} order by smn_base.smn_servicios.svc_descripcion asc