select
		smn_comercial.smn_rel_detalle_ingrediente.smn_rel_detalle_ingrediente_id,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_solicitud_servicio_entregas_detalle_id,
	smn_comercial.smn_v_ingredientes.item as smn_ingredientes_id
from
	smn_comercial.smn_rel_detalle_ingrediente
	inner join smn_comercial.smn_ingredientes on smn_comercial.smn_ingredientes.smn_ingredientes_id = smn_comercial.smn_rel_detalle_ingrediente.smn_ingredientes_id
	inner join smn_comercial.smn_solicitud_servicio_entregas_detalle on smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_solicitud_servicio_entregas_detalle_id = smn_comercial.smn_rel_detalle_ingrediente.smn_solicitud_servicio_entregas_detalle_id
	left outer join smn_comercial.smn_v_ingredientes on smn_comercial.smn_v_ingredientes.id= smn_comercial.smn_rel_detalle_ingrediente.smn_ingredientes_id
	left outer join smn_comercial.smn_catalogo_item_comercio on smn_comercial.smn_catalogo_item_comercio.smn_catalogo_item_comercio_id = smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_catalogo_item_comercio_id
	left outer join smn_base.smn_item on smn_base.smn_item.smn_item_id = smn_comercial.smn_catalogo_item_comercio.smn_item_rf
where
	smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_solicitud_servicio_entregas_detalle_id=${fld:id2}