INSERT INTO smn_comercial.smn_cliente
(
	smn_cliente_id,
	smn_clasificacion_cliente_id,
	smn_clase_auxiliar_rf,
	smn_auxiliar_rf,
	smn_clasificacion_abc_rf,
	smn_sector_economico_rf,
	cli_nacional_ext,
	cli_vigencia,
	cli_estatus,
	cli_idioma,
	cli_usuario,
	cli_fecha_registro,
	cli_hora,
	smn_forma_pago_rf,
	smn_condicion_financiera_rf,
	smn_promotor_rf
)
VALUES
(
	${seq:currval@smn_comercial.seq_smn_cliente},
	${fld:smn_clasificacion_cliente_id},
	${fld:smn_clase_auxiliar_rf},
	${fld:smn_auxiliar_rf},
	${fld:smn_clasificacion_abc_rf},
	${fld:smn_sector_economico_rf},
	${fld:cli_nacional_ext},
	{d'${def:date}'},
	${fld:cli_estatus},
	'${def:locale}',
	'${def:user}',
	{d'${def:date}'},
	'${def:time}',
	${fld:smn_forma_pago_rf},
	${fld:smn_condicion_financiera_rf},
	${fld:smn_promotor_rf}
)
