select
		smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_solicitud_servicio_entregas_cabecera_id,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_catalogo_item_comercio_id,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_unidad_medida_rf,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_cantidad,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_requirimientos,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_precio_ml,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_moneda_rf,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_precio_ma,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_monto_moneda_local,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_monto_moneda_alterna,
	smn_comercial.smn_solicitud_servicio_entregas_detalle.sed_fecha_registro
from
	smn_comercial.smn_solicitud_servicio_entregas_detalle 
where
	smn_comercial.smn_solicitud_servicio_entregas_detalle.smn_solicitud_servicio_entregas_detalle_id = ${fld:id}
