select
		smn_comercial.smn_pedido_imp_deducc_detalle.smn_codigos_impuestos_rf
from
		smn_comercial.smn_pedido_imp_deducc_detalle
where
		smn_comercial.smn_pedido_imp_deducc_detalle.smn_codigos_impuestos_rf = ${fld:smn_codigos_impuestos_rf}
