INSERT INTO smn_comercial.smn_pedido_detalle
(
	smn_pedido_detalle_id,
	smn_pedido_cabecera_id,
	pde_naturaleza,
	smn_servicios_rf,
	smn_item_rf,
	smn_activo_fijo_rf,
	pde_cantidad_oferta,
	pde_cantidad_pedido,
	pde_cantidad_aprobada,
	pde_precio,
	pde_monto,
	smn_moneda_rf,
	smn_tasa_rf,
	pde_precio_moneda_alterna,
	pde_monto_moneda_alterna,
	pde_especificaciones_pedido,
	pde_fecha_requerida,
	pde_observaciones,
	pde_estatus,
	pde_idioma,
	pde_usuario,
	pde_fecha_registro,
	pde_hora
)
VALUES
(
	${seq:currval@smn_comercial.seq_smn_pedido_detalle},
	${fld:smn_pedido_cabecera_id},
	${fld:pde_naturaleza},
	${fld:smn_servicios_rf},
	${fld:smn_item_rf},
	${fld:smn_activo_fijo_rf},
	${fld:pde_cantidad_oferta},
	${fld:pde_cantidad_pedido},
	${fld:pde_cantidad_aprobada},
	${fld:pde_precio},
	${fld:pde_monto},
	${fld:smn_moneda_rf},
	${fld:smn_tasa_rf},
	${fld:pde_precio_moneda_alterna},
	${fld:pde_monto_moneda_alterna},
	${fld:pde_especificaciones_pedido},
	${fld:pde_fecha_requerido},
	${fld:pde_observaciones},
	${fld:pde_estatus},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
);

UPDATE smn_comercial.smn_pedido_cabecera SET
	smn_moneda_rf=${fld:smn_moneda_rf},
	smn_tasa_rf=${fld:smn_tasa_rf}

WHERE
	smn_pedido_cabecera_id=${fld:smn_pedido_cabecera_id}
