select
	smn_comercial.smn_factura_impresion_detalle.smn_grupo_titulo_impresion_rf as titulo_id,
    smn_comercial.smn_factura_impresion_detalle.fim_codigo,
	smn_comercial.smn_factura_impresion_detalle.fim_descripcion,
	smn_comercial.smn_factura_impresion_detalle.fim_monto_ml,
	smn_comercial.smn_factura_impresion_detalle.fim_cantidad
from
    smn_comercial.smn_pedido_cabecera
	INNER JOIN
		smn_comercial.smn_factura_impresion_detalle on smn_comercial.smn_pedido_cabecera.smn_pedido_cabecera_id = smn_comercial.smn_factura_impresion_detalle.smn_factura_cabecera_id
	INNER JOIN
		smn_base.smn_grupo_titulo_impresion on smn_comercial.smn_factura_impresion_detalle.smn_grupo_titulo_impresion_rf = smn_base.smn_grupo_titulo_impresion.smn_grupo_titulo_impresion_id
	INNER JOIN	
		smn_base.smn_factura_cabecera on smn_comercial.smn_factura_impresion_detalle.smn_factura_cabecera_id = smn_comercial.smn_factura_cabecera.smn_factura_cabecera_id
	INNER JOIN 
		smn_comercial.smn_pedido_detalle on smn_comercial.smn_factura_impresion_detalle.smn_pedido_detalle_id = smn_comercial.smn_pedido_detalle.smn_pedido_detalle_id
	INNER JOIN 
		smn_comercial.smn_pedido_detalle on smn_comercial.smn_factura_impresion_detalle.smn_pedido_componente_id = smn_comercial.smn_pedido_componentes.smn_pedido_componentes_id		
where
    smn_comercial.smn_factura_cabecera.smn_factura_cabecera_id = ${fld:id}
