INSERT INTO smn_base.smn_rel_auxiliar_direccion
(
	smn_rel_auxiliar_direccion_id,
	smn_clase_auxiliar_id,
	smn_auxiliar_id,
	smn_direccion_id,
	rad_tipo_direccion,
	rad_status,
	rad_fecha_vigencia,
	rad_idioma,
	rad_usuario,
	rad_fecha_registro,
	rad_hora,
	smn_zona_rf
)
VALUES
(
	${seq:nextval@smn_base.seq_smn_rel_auxiliar_direccion},
	?,
	?,
	?,
	?,
	?,
	?,
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	?
)
