INSERT INTO smn_comercial.smn_orden_servicio_detalle
(
	smn_orden_servicio_detalle_id,
	smn_orden_cab_det_servicio_id,
	smn_servicios_rf,
	smn_item_rf,
	smn_componentes_rf,
	osd_cantidad,
	smn_tipo_componente,
	smn_grupo_prestador_rf,
	smn_prestador_servicio_rf,
	smn_nivel_estructura_rf,
	osd_estatus,
	osd_idioma,
	osd_usuario,
	osd_fecha_registro,
	osd_hora
)
VALUES
(
	${seq:currval@smn_comercial.seq_smn_orden_servicio_detalle},
	${fld:smn_orden_cab_det_servicio_id},
	${fld:smn_servicios_rf},
	${fld:smn_item_rf},
	${fld:smn_componentes_rf},
	${fld:osd_cantidad},
	${fld:smn_tipo_componente},
	${fld:smn_grupo_prestador_rf},
	${fld:smn_prestador_servicio_rf},
	${fld:smn_nivel_estructura_rf},
	${fld:osd_estatus},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
