select
		smn_comercial.smn_detalle_documento_titulo_imp.smn_detalle_documento_titulo_imp_id,
	smn_comercial.smn_documento_grp_titulo_imp.smn_documento_grp_titulo_imp_id,
	smn_comercial.smn_documento_grp_titulo_imp.rdi_idioma as rdi_idioma_pl0,
select
		smn_comercial.smn_detalle_documento_titulo_imp.smn_detalle_documento_titulo_imp_id,
select
		smn_comercial.smn_detalle_documento_titulo_imp.smn_detalle_documento_titulo_imp_id,
select
		smn_comercial.smn_detalle_documento_titulo_imp.smn_detalle_documento_titulo_imp_id,
select
		smn_comercial.smn_detalle_documento_titulo_imp.smn_detalle_documento_titulo_imp_id,
	smn_comercial.smn_detalle_documento_titulo_imp.smn_documento_grp_titulo_imp_id,
	smn_comercial.smn_detalle_documento_titulo_imp.smn_item_servicio_rf,
	smn_comercial.smn_detalle_documento_titulo_imp.smn_id_rf,
	smn_comercial.smn_detalle_documento_titulo_imp.smn_componentes_rf,
	smn_comercial.smn_detalle_documento_titulo_imp.dgi_idioma,
	smn_comercial.smn_detalle_documento_titulo_imp.dgi_usuario,
	smn_comercial.smn_detalle_documento_titulo_imp.dgi_fecha_registro,
	smn_comercial.smn_detalle_documento_titulo_imp.dgi_hora,
		smn_comercial.smn_detalle_documento_titulo_imp.smn_detalle_documento_titulo_imp_id
	
from
	smn_comercial.smn_documento_grp_titulo_imp,
	smn_comercial.smn_detalle_documento_titulo_imp,
	smn_comercial.smn_item_servicio
where
	smn_comercial.smn_documento_grp_titulo_imp.smn_documento_grp_titulo_imp_id=smn_comercial.smn_detalle_documento_titulo_imp.smn_documento_grp_titulo_imp_id
	and smn_comercial.smn_detalle_documento_titulo_imp.smn_item_servicio_rf=smn_comercial.smn_item_servicio.smn_item_servicio_id
order by
		
