INSERT INTO smn_cobranzas.smn_mov_documento_cob_detalle
(
	smn_mov_documento_cob_det_id,
	smn_mov_documento_cob_cab_id,
	smn_tipo_documento_id,
	smn_documento_id,
	mdd_numero_documento,
	smn_cliente_rf,
	smn_centro_costo_rf,
	mdd_monto_ml,
	smn_moneda_rf,
	mdd_monto_ma,
	mdd_fecha_pago,
	smn_tasa_rf,
	mdd_diferencia_cambiario,
	mdd_idioma,
	mdd_usuario,
	mdd_fecha_registro,
	mdd_hora,
	mdd_saldo_ml,
	mdd_sald_ma,
	'RE'
)
VALUES
(
	${seq:nextval@smn_cobranzas.seq_smn_mov_documento_cob_detalle},
	(select last_value from smn_cobranzas.seq_smn_mov_documento_cob_cab),
	(select smn_cobranzas.smn_documento.smn_tipo_documento_id from smn_cobranzas.smn_documento where smn_cobranzas.smn_documento.smn_documento_general_rf = (select smn_comercial.smn_documento.smn_documentos_generales_rf from smn_comercial.smn_documento where smn_comercial.smn_documento.smn_documento_id =  ${fld:smn_documento_id})),
	(select smn_cobranzas.smn_documento.smn_documento_id from smn_cobranzas.smn_documento where smn_cobranzas.smn_documento.smn_documento_general_rf=(select smn_comercial.smn_documento.smn_documentos_generales_rf from smn_comercial.smn_documento where smn_comercial.smn_documento.smn_documento_id = ${fld:smn_documento_id})),
	${fld:mdd_numero_documento},
	${fld:smn_cliente_rf},
	${fld:smn_centro_costo_rf},
	${fld:mdd_monto_ml},
	${fld:smn_moneda_rf},
	${fld:mdd_monto_ma},
	{d '${def:date}'},
	${fld:smn_tasa_rf},
	0,
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:mdd_saldo_ml},
	${fld:mdd_saldo_ma},
	'RE'
)
