INSERT INTO smn_caja.smn_mov_caja_detalle
(
	smn_mov_caja_detalle_id,
	smn_mov_caja_cabecera_id,
	mcd_tipo_producto,
	smn_id_rf,
	mcd_monto_por_pagar_ml,
	mcd_saldo_pago_ml,
	mcd_monto_por_pagar_ma,
	mcd_saldo_pago_ma,
	smn_moneda_rf,
	smn_tasa_rf,
	mcd_idioma,
	mcd_usuario,
	mcd_fecha_registro,
	mcd_hora
)
VALUES
(
	${seq:nextval@smn_caja.seq_smn_mov_caja_detalle},
	${fld:smn_mov_caja_cabecera_id},
	'IT',
	${fld:smn_id_rf},
	${fld:monto},
	${fld:saldo},
	${fld:precio_ma},
	${fld:monto_ma},
	${fld:moneda},
	${fld:tasa},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
);
