select SUM(smn_solicitud_servicio_entregas_detalle.sed_monto_moneda_local) as monto, MAX(smn_comercial.smn_catalogo_item_comercio.cic_tiempo_sug_preparacion) as tiempo
from smn_comercial.smn_solicitud_servicio_entregas_detalle
inner join smn_comercial.smn_solicitud_servicio_entregas_cabecera on smn_comercial.smn_solicitud_servicio_entregas_cabecera.smn_solicitud_servicio_entregas_cabecera_id = smn_solicitud_servicio_entregas_detalle.smn_solicitud_servicio_entregas_cabecera_id
inner join smn_comercial.smn_catalogo_item_comercio on smn_comercial.smn_catalogo_item_comercio.smn_catalogo_item_comercio_id = smn_solicitud_servicio_entregas_detalle.smn_catalogo_item_comercio_id
where 
	smn_comercial.smn_solicitud_servicio_entregas_cabecera.smn_solicitud_servicio_entregas_cabecera_id=${fld:id2}