select smn_comercial.smn_pago_punto_venta.ppv_monto_devuelto_ml as saldo_devuelto from smn_comercial.smn_pago_punto_venta 
where
smn_comercial.smn_pago_punto_venta.smn_pedido_cabecera_id=${fld:id2} order by smn_comercial.smn_pago_punto_venta.ppv_hora desc limit 1