INSERT INTO smn_comercial.smn_pedido_cabecera
(
	smn_pedido_cabecera_id,
	smn_documento_id,
	pca_numero_pedido,
	smn_cliente_id,
	smn_usuario_rf,
	pca_descripcion,
	pca_fecha_requerida,
	smn_entidad_rf,
	smn_sucursal_rf,
	smn_area_servicio_rf,
	smn_unidad_servicio_rf,
	smn_almacen_rf,
	smn_centro_costo_rf,
	smn_centro_facturacion_id,
	smn_sub_centro_facturacion_id,
	smn_tipo_linea_comercial_id,
	smn_linea_comercial_id,
	pca_monto_pedido_ma,
	pca_monto_descuento_ml,
	pca_monto_descuento_ma,
	pca_monto_impuesto_ml,
	pca_monto_impuesto_ma,
	pca_monto_neto_ml,
	pca_monto_neto_ma,
	smn_moneda_rf,
	smn_tasa_rf,
	pca_estatus,
	pca_estatus_pago,
	pca_fecha_vencimiento,
	pca_idioma,
	pca_usuario,
	pca_fecha_registro,
	pca_hora,
	smn_auxiliar_rf,
	smn_modulo_rf
)
VALUES
(
	${seq:currval@smn_comercial.seq_smn_pedido_cabecera},
	(select smn_comercial.smn_rel_centro_fac_documento.smn_documento_id from smn_comercial.smn_centro_facturacion inner join smn_comercial.smn_rel_centro_fac_documento on smn_comercial.smn_rel_centro_fac_documento.smn_centro_facturacion_id = smn_comercial.smn_centro_facturacion.smn_centro_facturacion_id
		where smn_comercial.smn_rel_centro_fac_documento.smn_centro_facturacion_id=${fld:smn_centro_facturacion_id_1} limit 1),
	${seq:nextval@smn_comercial.seq_smn_numero_pedido},
	${fld:smn_cliente},
	(select smn_base.smn_usuarios.smn_usuarios_id from smn_base.smn_usuarios LEFT OUTER JOIN smn_seguridad.s_user on smn_seguridad.s_user.user_id = smn_base.smn_usuarios.smn_user_rf where smn_seguridad.s_user.userlogin = '${def:user}' limit 1),
	'Generado desde el punto de venta',
	{d '${def:date}'},
	${fld:smn_entidad_rf},
	${fld:smn_sucursal_rf},
	${fld:smn_area_servicio_rf},
	${fld:smn_unidad_servicio_rf},
	${fld:smn_almacen_rf},
	${fld:smn_centro_costo_rf},
	${fld:smn_centro_facturacion_id_1},
	${fld:smn_sub_centro_facturacion_id_1},
	(select smn_comercial.smn_tipo_linea_comercial.smn_tipo_linea_comercial_id from smn_comercial.smn_tipo_linea_comercial inner join smn_comercial.smn_linea_comercial on smn_comercial.smn_linea_comercial.smn_tipo_linea_comercial_id = smn_comercial.smn_tipo_linea_comercial.smn_tipo_linea_comercial_id  inner join smn_comercial.smn_rel_centro_fac_linea on smn_comercial.smn_rel_centro_fac_linea.smn_linea_comercial_id = smn_comercial.smn_linea_comercial.smn_linea_comercial_id where smn_comercial.smn_rel_centro_fac_linea.smn_centro_facturacion_id=${fld:smn_centro_facturacion_id_1}),
	(select smn_comercial.smn_linea_comercial.smn_linea_comercial_id from smn_comercial.smn_linea_comercial inner join smn_comercial.smn_rel_centro_fac_linea on smn_comercial.smn_rel_centro_fac_linea.smn_linea_comercial_id = smn_comercial.smn_linea_comercial.smn_linea_comercial_id where smn_comercial.smn_rel_centro_fac_linea.smn_centro_facturacion_id=${fld:smn_centro_facturacion_id_1}),
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	(select smn_base.smn_baremos.smn_moneda_rf from smn_base.smn_baremos where smn_base.smn_baremos.smn_baremos_id=${fld:BaremosG} limit 1),
	(select smn_base.smn_tasas_de_cambio.smn_tasas_de_cambio_id as id from smn_base.smn_tasas_de_cambio inner join smn_base.smn_monedas on smn_base.smn_monedas.smn_monedas_id = smn_base.smn_tasas_de_cambio.smn_monedas_id
where smn_base.smn_tasas_de_cambio.smn_monedas_id=(select smn_base.smn_baremos.smn_moneda_rf from smn_base.smn_baremos where smn_base.smn_baremos.smn_baremos_id=${fld:BaremosG} limit 1) and smn_base.smn_tasas_de_cambio.tca_fecha_vigencia = current_date limit 1),
	'RE',
	'PE',
	{d '${def:date}'},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_auxiliar_rf},
	(select smn_base.smn_modulos.smn_modulos_id from smn_base.smn_modulos where smn_base.smn_modulos.mod_codigo = 'SMN_CME')
)
