INSERT INTO smn_comercial.smn_orden_servicio_detalle
(
	smn_orden_servicio_detalle_id,
	smn_orden_servicio_id,
	smn_servicios_rf,
	smn_item_rf,
	smn_componentes_rf,
	osd_cantidad,
	smn_tipo_componente,
	smn_grupo_prestador_rf,
	smn_prestador_servicio_rf,
	smn_nivel_estructura_rf,
	osd_estatus,
	osd_fecha_registro
)
VALUES
(
	${seq:nextval@smn_comercial.seq_smn_orden_servicio_detalle},
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	{d '${def:date}'}
)
