select
		smn_comercial.smn_rel_cliente_medio_pago.smn_rel_cliente_medio_pago_id,
select
		smn_comercial.smn_rel_cliente_medio_pago.smn_rel_cliente_medio_pago_id,
where
select
		smn_comercial.smn_rel_cliente_medio_pago.smn_rel_cliente_medio_pago_id,
		smn_comercial.smn_rel_cliente_medio_pago.smn_rel_cliente_medio_pago_id,
	smn_comercial.smn_rel_cliente_medio_pago.smn_cliente_id,
	smn_comercial.smn_rel_cliente_medio_pago.smn_cliente_id,
	smn_comercial.smn_rel_cliente_medio_pago.smn_medio_pago_rf
	smn_comercial.smn_rel_cliente_medio_pago.smn_medio_pago_rf
	
	
from
	smn_comercial.smn_rel_cliente_medio_pago
	smn_comercial.smn_rel_cliente_medio_pago
