select
		smn_comercial.smn_rel_cliente_servicio.smn_rel_cliente_servicio_id,
select
		smn_comercial.smn_rel_cliente_servicio.smn_rel_cliente_servicio_id,
where
select
		smn_comercial.smn_rel_cliente_servicio.smn_rel_cliente_servicio_id,
		smn_comercial.smn_rel_cliente_servicio.smn_rel_cliente_servicio_id,
	smn_comercial.smn_rel_cliente_servicio.smn_cliente_id,
	smn_comercial.smn_rel_cliente_servicio.smn_cliente_id,
	smn_comercial.smn_rel_cliente_servicio.smn_servicio_rf
	smn_comercial.smn_rel_cliente_servicio.smn_servicio_rf
	
	
from
	smn_comercial.smn_rel_cliente_servicio
	smn_comercial.smn_rel_cliente_servicio
