select
	smn_solicitud_servicio_entregas_detalle_id	
from 
	smn_comercial.smn_solicitud_servicio_entregas_detalle
where
	smn_solicitud_servicio_entregas_detalle_id = ${fld:smn_solicitud_servicio_entregas_detalle_id}
	