INSERT INTO smn_comercial.smn_control_fiscal_documento
(
	smn_control_fiscal_documento_id,
	smn_documento_id,
	smn_proveedor_rf,
	cfd_numero_documento_fiscal_inicial,
	cfd_numero_documento_fiscal_final,
	cfd_ultimo_numero_fiscal_usado,
	cfd_fecha_solicitud,
	cfd_fecha_recepcion,
	cfd_serie,
	cfd_estatus,
	cfd_idioma,
	cfd_usuario,
	cfd_fecha_registro,
	cfd_hora
)
VALUES
(
	${seq:currval@smn_comercial.seq_smn_control_fiscal_documento},
	${fld:smn_documento_id},
	${fld:smn_proveedor_rf},
	${fld:cfd_numero_documento_fiscal_inicial},
	${fld:cfd_numero_documento_fiscal_final},
	${fld:cfd_ultimo_numero_fiscal_usado},
	${fld:cfd_fecha_solicitud},
	${fld:cfd_fecha_recepcion},
	${fld:cfd_serie},
	${fld:cfd_estatus},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
