select
	smn_solicitud_servicio_entregas_cabecera_id	
from 
	smn_comercial.smn_solicitud_servicio_entregas_cabecera
where
	smn_solicitud_servicio_entregas_cabecera_id = ${fld:smn_solicitud_servicio_entregas_cabecera_id}
	