select smn_base.smn_servicios.smn_servicios_id as smn_servicios_rf, smn_base.smn_servicios.svc_descripcion
from smn_comercial.smn_rel_orden_servicio
left outer join smn_base.smn_servicios on smn_base.smn_servicios.smn_servicios_id = smn_comercial.smn_rel_orden_servicio.smn_servicios_rf
inner join smn_comercial.smn_orden_cab_det_servicio on smn_comercial.smn_orden_cab_det_servicio.smn_orden_servicio_id = smn_comercial.smn_rel_orden_servicio.smn_orden_servicio_id
where smn_comercial.smn_orden_cab_det_servicio.smn_orden_cab_det_servicio_id=${fld:id} order by smn_base.smn_servicios.svc_codigo desc