SELECT DISTINCT
	smn_comercial.smn_pedido_componentes.smn_pedido_cabecera_id,
	smn_comercial.smn_pedido_componentes.smn_pedido_detalle_id,
	smn_comercial.smn_pedido_componentes.smn_pedido_componentes_id,
	smn_comercial.smn_factura_cabecera.smn_factura_cabecera_id,
	smn_comercial.smn_pedido_componentes.pco_cantidad,
	smn_comercial.smn_pedido_componentes.smn_precio_ml_rf,
	smn_comercial.smn_pedido_componentes.smn_precio_ma,
	smn_comercial.smn_pedido_componentes.smn_precio_ml_rf as pco_monto_ml,
	smn_comercial.smn_pedido_componentes.smn_precio_ma as smn_monto_ma,
	smn_base.smn_servicios.svc_codigo as codigo,
	smn_base.smn_servicios.svc_descripcion as descripcion,
	smn_comercial.smn_pedido_componentes.smn_moneda_rf,
	smn_comercial.smn_pedido_componentes.smn_tasa_rf,
	smn_comercial.smn_pedido_cabecera.pca_numero_pedido,
	smn_comercial.smn_pedido_componentes.smn_grupo_titulo_impresion_rf,
	smn_comercial.smn_pedido_componentes.smn_prestador_servicio_rf
FROM
	smn_comercial.smn_pedido_componentes
	INNER JOIN smn_comercial.smn_pedido_cabecera ON smn_comercial.smn_pedido_cabecera.smn_pedido_cabecera_id = smn_comercial.smn_pedido_componentes.smn_pedido_cabecera_id
	INNER JOIN smn_comercial.smn_pedido_detalle ON smn_comercial.smn_pedido_detalle.smn_pedido_cabecera_id = smn_comercial.smn_pedido_componentes.smn_pedido_cabecera_id
	left join smn_comercial.smn_rel_pedido_factura on smn_comercial.smn_rel_pedido_factura.smn_pedido_cabecera_id = smn_comercial.smn_pedido_cabecera.smn_pedido_cabecera_id 
	left join smn_comercial.smn_factura_cabecera on smn_comercial.smn_factura_cabecera.smn_factura_cabecera_id = smn_comercial.smn_pedido_cabecera.smn_pedido_cabecera_id 
	inner join smn_base.smn_servicios on smn_base.smn_servicios.smn_servicios_id = smn_comercial.smn_pedido_componentes.smn_servicio_rf
	inner join smn_base.smn_componentes on smn_base.smn_componentes.smn_componentes_id = smn_comercial.smn_pedido_componentes.smn_componente_rf
where 
	smn_comercial.smn_pedido_componentes.smn_pedido_cabecera_id= ${fld:smn_pedido_cabecera_id}