INSERT INTO smn_caja.smn_mov_caja_cabecera
(
	smn_mov_caja_cabecera_id,
	smn_caja_id,
	smn_modulo_rf,
	mcc_documento_rf,
	mcc_cod_descripcion_orig,
	smn_num_doc_origen_rf,
	mcc_doc_referencia,
	smn_documento_id,
	mcc_documento_numero,
	smn_clase_auxiliar_rf,
	smn_auxiliar_rf,
	smn_clase_auxiliar_pagador_rf,
	smn_auxiliar_pagador_rf,
	mcc_monto_ml_documento,
	mcc_saldo_ml_documento,
	mcc_monto_ma_documento,
	mcc_saldo_ma_documento,
	smn_moneda_rf,
	smn_tasa_rf,
	smn_estatus_cobro,
	mcc_estatus_registro,
	mcc_idioma,
	mcc_usuario,
	mcc_fecha_registro,
	mcc_hora
)
VALUES
(
	${seq:nextval@smn_caja.seq_smn_mov_caja_cabecera},
	${fld:caja},
	(select smn_base.smn_modulos.smn_modulos_id from smn_base.smn_modulos where smn_base.smn_modulos.mod_codigo = 'SMN_CME'),
	${fld:documento},
	(select smn_comercial.smn_documento.dcf_codigo||'-'|| smn_comercial.smn_documento.dcf_descripcion as descripcion from smn_comercial.smn_pedido_cabecera inner join smn_comercial.smn_documento on smn_comercial.smn_documento.smn_documento_id = smn_comercial.smn_pedido_cabecera.smn_documento_id inner join smn_base.smn_documentos_generales on smn_base.smn_documentos_generales.smn_documentos_generales_id = smn_comercial.smn_documento.smn_documentos_generales_rf where smn_comercial.smn_pedido_cabecera.smn_pedido_cabecera_id=${fld:smn_pedido_cabecera_id}),
	(select smn_base.smn_documentos_generales.smn_documentos_generales_id from smn_comercial.smn_pedido_cabecera inner join smn_comercial.smn_documento on smn_comercial.smn_documento.smn_documento_id = smn_comercial.smn_pedido_cabecera.smn_documento_id inner join smn_base.smn_documentos_generales on smn_base.smn_documentos_generales.smn_documentos_generales_id = smn_comercial.smn_documento.smn_documentos_generales_rf where smn_comercial.smn_pedido_cabecera.smn_pedido_cabecera_id=${fld:smn_pedido_cabecera_id}),
	${fld:numero_referencia},
	(select smn_caja.smn_rel_caja_documento.smn_documento_id from smn_comercial.smn_pedido_cabecera inner join smn_comercial.smn_centro_facturacion on smn_comercial.smn_centro_facturacion.smn_centro_facturacion_id = smn_comercial.smn_pedido_cabecera.smn_centro_facturacion_id inner join smn_caja.smn_caja on smn_caja.smn_caja.smn_caja_id = smn_comercial.smn_centro_facturacion.smn_caja_rf inner join smn_caja.smn_rel_caja_documento on smn_caja.smn_rel_caja_documento.smn_caja_id = smn_comercial.smn_centro_facturacion.smn_caja_rf where smn_comercial.smn_pedido_cabecera.smn_pedido_cabecera_id=${fld:smn_pedido_cabecera_id} limit 1),
	${seq:nextval@smn_caja.seq_documento_numero},
	${fld:clase_comprador},
	${fld:smn_auxiliar_rf},
	${fld:clase_comprador},
	${fld:smn_auxiliar_rf},
	${fld:monto_ml},
	${fld:saldo_ml},
	${fld:monto_ma},
	${fld:saldo_ma},
	${fld:moneda},
	${fld:tasa},
	'PA',
	'GE',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
) RETURNING smn_mov_caja_cabecera_id;
