INSERT INTO smn_comercial.smn_presupuesto_componente
(
	smn_presupuesto_componente_id,
	smn_presupuesto_detalle_id,
	smn_presupuesto_id,
	smn_servicios_rf,
	smn_tipos_componentes_rf,
	smn_componentes_rf,
	smn_grupo_prestador_rf,
	smn_prestadores_servicios_rf,
	prc_porcentaje_prestador,
	prc_forma_calculo_rf,
	prc_visible_rf,
	prc_cantidad,
	prc_precio_ml,
	prc_precio_ma,
	smn_moneda_rf,
	prc_monto_ml,
	prc_monto_ma,
	prc_monto_impuesto_ml,
	prc_monto_impuesto_ma,
	prc_monto_descuento_ml,
	prc_monto_descuento_ma,
	prc_monto_incremento_ml,
	prc_monto_incremento_ma,
	prc_monto_neto_ml,
	prc_monto_neto_ma,
	prc_idioma,
	prc_usuario,
	prc_fecha_registro,
	prc_hora
)
VALUES
(
	${seq:nextval@smn_comercial.seq_smn_presupuesto_componente},
	${fld:smn_presupuesto_detalle_id},
	${fld:smn_presupuesto_id},
	${fld:smn_servicios_rf},
	${fld:smn_tipo_componente},
	${fld:smn_componentes_rf},
	${fld:smn_grupo_prestador_rf},
	${fld:smn_prestador_servicio_rf},
	${fld:cmp_porcentaje},
	${fld:smn_forma_calculo_rf},
	${fld:smn_visible_rf},
	${fld:prd_cantidad},
	(case when ${fld:precio} is null then 0 else ${fld:precio} end),
	(case when ${fld:precio_ma} is null then 0 else ${fld:precio_ma} end),
	${fld:smn_moneda_rf},
	(case when ${fld:precio} is null then 0 else ${fld:precio} end),
	(case when ${fld:precio_ma} is null then 0 else ${fld:precio_ma} end),
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
